=== 2lambda123/nasa-trick/trick_test/requirements_docs/DTD/TopLevelReqs.dtd
<!-- Trick Requirements definition -->
<!-- V 1.0 -->

<!ELEMENT requirement		(#PCDATA | requirement)*>

<!ATTLIST requirement statement		CDATA #IMPLIED>
<!ATTLIST requirement tag		    CDATA #IMPLIED>
<!ATTLIST requirement note		    CDATA #IMPLIED>
<!ATTLIST requirement verify        CDATA #IMPLIED>

=== 2lambda123/nasa-trick/trick_test/requirements_docs/src_xml/TopLevelReqs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TopLevelReqs PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../DTD/TopLevelReqs.dtd">

<requirement
  statement="[HEADER] Software Description">
  <requirement 
  	statement="[HEADER] Functional Requirements">
	<requirement 
	  statement="[HEADER] Simulation Building">
	  <requirement  
	  	statement="Trick shall provide a utility, the Configuration Processor
		(CP), to build a simulation in accordance with the jobs and data
		structures defined in the simulation definition file."
		verify="Type &quot;CP&quot; in a simulation folder in order to build."/>
	  <requirement 
		statement="CP shall execute the Interface Code Generator (ICG) on all 
		header files required by the simulation.">
		<requirement 
		  statement="ICG shall process C and C++ header files to gather data 
		  structure types."
		  verify=""/>
		<requirement 
		  statement="ICG shall generate source files detailing the layout of 
		  data structures found in each header file."
		  verify="Look for the folder &quot;io_src&quot; in the Trick model folder; 
		  this is generated by ICG."/>
		<requirement 
		  statement="ICG shall generate extensible markup language (XML) auto 
		  documentation detailing the contents of each processed header file."
		  verify=""/>
	  </requirement>
	  <requirement 
		statement="CP shall execute the Module Interface Specification (MIS) 
		utility on all source code files required by the simulation.">
		<requirement 
		  statement="MIS shall process C and C++ source code files to gather 
		  function call prototypes."/>
		<requirement 
		  statement="MIS shall generate the list of object files specified within 
		  the Trick headers in the source files."
		  verify="In the Trick model folder, look for a separate object folder after
		  compiling. This is generated by MIS."/>
		<requirement 
		  statement="MIS shall generate XML auto documentation detailing the 
		  contents of each processed source file."/>
	  </requirement>
	  <requirement 
		statement="CP shall generate a makefile for building the simulation 
		model code.">
		<requirement
		  statement="The makefile shall provide the capability for the user to 
		  override any rule or variable specified."
		  verify="If CP is successful, look in sim folder for &quot;makefile.&quot;
		  This file has read and write permissions."/>
	  </requirement>
	  <requirement 
		statement="CP shall generate source code capable of calling all jobs 
		listed within the simulation definition file."/>
	  <requirement 
		statement="CP shall execute &quot;make&quot; to compile and link a simulation 
		executable."/>
	  <requirement 
		statement="Trick shall support the incorporation of external model 
		libraries."/>
	</requirement>

	<requirement 
	  statement="[HEADER] Executive">
	  <requirement 
		statement="Trick shall support both cyclic and discrete model jobs 
		(job classes).">
		<requirement 
		  statement="Trick shall be capable of discrete job execution scheduling 
		  for each of the following conditions:">
		  <requirement 
			statement="During simulation initialization. (Initialization job class)"/>
		  <requirement 
			statement="Prior to a checkpoint reload. (Pre_Load_Checkpoint job class)"/>
		  <requirement 
			statement="Following a checkpoint reload. (Checkpoint Restart job class)"/>
		  <requirement 
			statement="Prior to checkpoint store. (Checkpoint job class)"/>
		  <requirement 
			statement="Prior to simulation termination. (Shutdown job class)"/>
		  <requirement 
			statement="Upon entering simulation freeze. (Freeze_init job class)"/>
		  <requirement 
			statement="Prior to entering cyclic operation from freeze. (Unfreeze 
			job class)"/>
		</requirement>
		<requirement 
		  statement="Trick shall be capable of periodic job execution scheduling 
		  for each of the following conditions:">
		  <requirement 
			statement="During simulation cyclic operation at a given simulation-
			frequency and simulation-time-offset. (Scheduled job class)"/>
		  <requirement 
			statement="At the top of frame during simulation cyclic (run) mode 
			at a specified frequency, for performing state integration. (Integration 
			job class)"/>
		  <requirement 
			statement="Immediately following the completion of Integration class 
			jobs. (Post_integration job class)"/>
		  <requirement 
			statement="Periodically, at a common frequency during freeze mode. 
			(Freeze job class)"/>
		  <requirement 
			statement="Periodically, at a user specified frequency and offset, 
			in its own process thread of execution with no restriction on whether or
			when it actually completes. (Asynchronous job class)"/>
		  <requirement 
			statement="Periodically, at a user specified frequency and offset 
			in its own process thread of execution with the restriction that the job
			must complete prior to its next scheduled execution. 
			(Asynchronous_must_Finish job class)"/>
		</requirement>
		<requirement 
		  statement="Trick shall be capable of scheduling jobs for execution 
		  for the following (special) conditions:">
		  <requirement 
			statement="Next execution time is the specified period (1 / specified
			freq), plus a random offset within the range of + /â€“  1 period. 
			(Random job class)"/>
		  <requirement 
			statement="Once during initialization mode and thereafter by the 
			Trick mechanism. (Derivative job class)"/>
		  <requirement 
			statement="Once during simulation cyclic (run) mode. Thereafter, the 
			job is responsible for scheduling itself. (Automatic job class)"/>
		  <requirement 
			statement="Once during simulation cyclic (run) mode. Thereafter, the 
			job is responsible for scheduling itself, though the job scheduler
			will ensure that it is always run last amongst jobs scheduled for the
			same time. (Automatic_last job class)"/>
		  <requirement 
			statement="Periodically at the rate of an associated class job, for 
			the purpose implementing dynamic events during state integration.
			(Dynamic_event job class)">
			<requirement 
				statement="The Trick executive shall flag the condition that the 
				value returned by the Dynamic_event class job is less than the 
				associated period."/>
		  </requirement>
		  <requirement 
			statement="For Monte Carlo simulation runs (only):">
			<requirement 
			  statement="Once when the master simulation is initialized. 
			  (Monte_Master_Init job class)"/>
			<requirement 
			  statement="Once before new data is dispatched to a slave. 
			  (Monte_Master_Pre job class)"/>
			<requirement 
			  statement="Once after the result is returned from a slave. 
			  (Monte_Master_Post job class)"/>
			<requirement 
			  statement="Once when the master simulation shuts down. 
			  (Monte_Master_Shutdown job class)"/>
			<requirement 
			  statement="Once when a slave is initialized. (Monte_Slave_Init 
			  job class)"/>
			<requirement 
			  statement="Once after new data is received from master simulation.  
			  (Monte_Slave_Pre job class)"/>
			<requirement 
			  statement="Once after a slave is completed. (sends result to the 
			  master) (Monte_Slave_Post job class)"/>
			<requirement 
			  statement="Once when monte carlo master communication is lost and 
			  a slave shuts down. (Monte_Slave_Shutdown job class)"/>
		  </requirement>
		  <requirement 
			statement="Immediately before or after (user specified) another 
			associated job to check a malfunction trigger. (Malfunction_trigger 
			job class)">
			<requirement 
			  statement="A malfunction_trigger class job shall return TRUE or FALSE."/>
		  </requirement>
		  <requirement 
			statement="Immediately before or after (user specified) an associated 
			job to execute a malfunction. (Malfunction job class)">
			<requirement 
			  statement="A malfunction class job shall only execute if its 
			  malfunction trigger condition is TRUE."/>
		  </requirement>
		</requirement>
	  </requirement>
	  <requirement 
		statement="Trick shall provide a malfunction insertion capability 
		that can override the value of any simulation variable or call a
		malfunction job at any time during the simulation."/>
	  <requirement 
		statement="Trick shall provide a malfunction trigger capability 
		that contains either a condition statement or a job statement that when
		evaluated as TRUE, will cause the malfunction action to occur."/>
	  <requirement 
		statement="Trick shall provide the capability to turn on/off 
		individual jobs."/>
	  <requirement 
		statement="Trick shall provide the capability to turn on/off 
		groups of jobs."/>
	  <requirement	
	  	statement="Trick shall provide the capability to turn on/off
	  	sim objects."/>
	  
	  <requirement 
	    statement="The following requirements need to be and moved to their
	    appropriate places. These requirements are about initiating checkpoints
	    not implementing them. I&apos;ll figure out where they need to go. -- Penn">
	  
		<requirement
		  statement="The Executive Scheduler shall copy all job information 
		  to a checkpointable array before a checkpoint is executed."/>
	    <requirement
	      statement="The Executive Scheduler shall be capable of initiating a checkpoint:">
	      <requirement
	      	statement="before initialization jobs are executed."/>
	      <requirement
	        statement="after initialization jobs are executed."/>
	      <requirement
	        statement="just prior to simulation termination."/>
	      <requirement
	        statement="at a time specified in the input file."/>
	    </requirement>
	    <requirement
	      statement="The simulation control panel shall be capable of initiating a 
	      checkpoint."/>
	  </requirement>
	</requirement>

	<requirement
	  statement="[HEADER] Scheduled Job Queue">
	  <requirement 
	    statement="Trick shall sequence cyclic model jobs in an execution 
	    frame and preserve that order throughout the simulation.">
	    <requirement
